# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-08 02:58
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lock',
            fields=[
                ('lock_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('is_locked', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='NFSServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('dns_name', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('quota_GB', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('locked', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RootPath',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('path', models.CharField(max_length=200)),
                ('capacity_GB', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('nfs_server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.NFSServer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('sub_path', models.CharField(max_length=200)),
                ('options', models.CharField(max_length=200)),
                ('allowed_hosts', models.CharField(default=b'*', max_length=200)),
                ('size_GB', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volumes', to=settings.AUTH_USER_MODEL)),
                ('root_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.RootPath')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
